### PR TITLE
Disable failovermethod in yumrepo on EL8

### PR DESCRIPTION
**Pull request by sircubbi**
#### Pull Request (PR) description
fix yumrepo-format for DNF (EL8 and newer)

#### This Pull Request (PR) fixes the following issues
failovermethod is not supported by DNF, so remove that line completly on
EL8 (and newer) as long as $priority is unset too.

### CODE REVIEW

**Comment by sircubbi** [comment]
Well, I cannot do against timeouts in the CI-pipeline. Could you please check or rerun it? Thanks.

**Comment by smortex** [comment]
GitHub deprecated git:// usage, can you please replace the repo URL in `.fixtures.yml` to use `https://` scheme instead ?

**Comment by sircubbi** [comment]
> GitHub deprecated `git://` usage, can you please replace the repo URLs in `.fixtures.yml` to use `https://` scheme instead ?

OK, that fixed the timeouts. However Ubuntu fails in die external apt-module now, with something that looks like a not fully populated `$facts`-variable for the operating-system.

**Comment by smortex** [comment]
Good, we are moving forward.

Puppet 6, the apt module and a failing access to `os.distro.codename` reminds me about lsb-release but I am surprised it does not fail on more Debian based operating systems.

Can you try to add this to see if it helps: https://github.com/voxpupuli/puppet-jenkins/commit/860af1e2e85f104904ed0e393387a6e38f254292 (the failure log shows that `lsb_release` is not found and instead of it facter use `/bin/sh -c cat\ /etc/lsb-release` which have less information).

**Comment by sircubbi** [comment]
> Good, we are moving forward.
> 
> Puppet 6, the apt module and a failing access to `os.distro.codename` reminds me about lsb-release but I am surprised it does not fail on more Debian based operating systems.
> 
> Can you try to add this to see if it helps: [voxpupuli/puppet-jenkins@860af1e](https://github.com/voxpupuli/puppet-jenkins/commit/860af1e2e85f104904ed0e393387a6e38f254292) (the failure log shows that `lsb_release` is not found and instead of it facter use `/bin/sh -c cat\ /etc/lsb-release` which have less information).

Thanks, that fixed the issue.

**Review by smortex — APPROVED** [review]
Nice! LGTM!

**Comment by bastelfreak** [comment]
thanks for fixing this!

**Pull request merged**
