### PR TITLE
modulesync 7.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 5.1.0

### CODE REVIEW

**Comment by bastelfreak** [comment]
@smortex looks like CentOS has some package conflicts. Is nodejs still supported there / did we setup the wrong repo / is epel broken maybe?

**Comment by root-expert** [comment]
Possibly NodeJS on EPEL is dead?

**Comment by bastelfreak** [comment]
Hey @sircubbi , do you have any ideas why the tests on CentOS 7 do not pass?

**Comment by sircubbi** [comment]
> Hey @sircubbi , do you have any ideas why the tests on CentOS 7 do not pass?

Hmmm, nothing really catches my eye. Seems like some timeout while still setting up the docker-environment, but no specific cause I fear.

**Comment by bastelfreak** [comment]
@sircubbi nownthe CI finally failed "properly", adter several docker-related issues. could you take a look again?

**Comment by sircubbi** [comment]
> @sircubbi nownthe CI finally failed "properly", adter several docker-related issues. could you take a look again?

It seems that `/usr/bin/npm` is not found. If you pull `nodejs` from EPEL you would also need to install the `npm`-Package from epel too (when using `nodesource` that is not necessary, since the `npm`-Command is already provided by the base-Package).

**Comment by kenyon** [comment]
I'll work on the EPEL failures. I can clean up the commit log once the code is good and the tests pass.

**Review by smortex — APPROVED** [review]
Wow, CI pass!

Well done @kenyon!

**Comment by evgeni** [comment]
This PR contains non modulesync changes:
* [Drop support for Debian 9, Ubuntu 16.04 and 18.04, FreeBSD 11 (EOL)](https://github.com/voxpupuli/puppet-nodejs/pull/453/commits/153c311d30435dcf86ba769fb880bec16d64a850) (breaking)
* [Add Puppet 8 support](https://github.com/voxpupuli/puppet-nodejs/pull/453/commits/581bb57f449d2edf643827a3045f594e252c9d2a) (feature)
* [Add support for RHEL 9 based distros](https://github.com/voxpupuli/puppet-nodejs/pull/453/commits/74cd95bcbef7b7a52b959fc871f1ce899a6d6a1a) (feature)

How do I teach GHC that…

**Comment by kenyon** [comment]
Yeah, there were pull requests closed for those, so not sure why GHC didn't include them.

**Pull request merged**
