### PR TITLE
remote source fix

### PR DESCRIPTION
**Pull request by onzyone**
quick fix for the following 

```
  nodejs::npm { 'node-wimoto':
    ensure  => 'present',
    package => 'node-wimoto',
    source  => 'onzyone/node-wimoto',
    target  => '/opt/packages',
  }
```

### CODE REVIEW

**Comment by igalic** [comment]
thanks, @onzyone!

now we just have to fix the failing spec tests: https://travis-ci.org/puppet-community/puppet-nodejs/jobs/81504502#L939

**Comment by juniorsysadmin** [comment]
Will this work for Git URLs as the source?

**Comment by onzyone** [comment]
I will look into this tonight. Is there a "how to" setup my git urls for testing?

**Comment by onzyone** [comment]
@igalic how do i see that the profile call is for this test?

1) nodejs::npm when run on Debian Wheezy with package set to express and source set to /local/folder the install_check should grep for /home/npm/package/node_modules//local/folder

**Comment by onzyone** [comment]
hello @igalic correct me if I am wrong, but the remaining tests are what I am trying to solve in the first place ...

**Comment by jyaworski** [comment]
Hello:

What is the status of this PR?

**Comment by jyaworski** [comment]
Closing due to lack of activity. Please re-open if still needed.

**Pull request closed without merging**
