### PR TITLE
Clean up acceptance spec helper

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by bastelfreak** [comment]
```
bastelfreak@tmu ~/modulesync_config/modules/puppet-nodejs $ puppet parser validate manifests/npm.pp 
bastelfreak@tmu ~/modulesync_config/modules/puppet-nodejs $ bundle exec rake lint
manifests/npm.pp:46:syntax:ERROR:Syntax error
Try running `puppet parser validate <file>`
bastelfreak@tmu ~/modulesync_config/modules/puppet-nodejs $ puppet parser validate manifests/npm.pp 
bastelfreak@tmu ~/modulesync_config/modules/puppet-nodejs $ 
```
no idea why this fails :(

**Comment by ekohl** [comment]
puppet-lint doesn't understand `"\\"` where `'\\'` does appear to work.

**Comment by ghoneycutt** [comment]
Created #407 to fix the syntax error.

**Comment by bastelfreak** [comment]
rebased the branch

**Pull request merged**
