### PR TITLE
Perform modulesync (0.3.0)

### PR DESCRIPTION
**Pull request by juniorsysadmin**
- Remove old nodesets as well

### CODE REVIEW

**Comment by bastelfreak** [comment]
uhm, did you create the PR with an old master as base? could you merge master into your PR?

**Comment by juniorsysadmin** [comment]
I seemed to have hit some weird GitHub caching. Should be fixed now.

**Comment by bastelfreak** [comment]
yep looks better :+1:

**Comment by jyaworski** [comment]
More deletions than additions. I like seeing that.

**Pull request merged**
