### PR TITLE
Node 6 is now available on EL6 & EL7

### PR DESCRIPTION
**Pull request by tapsboy**
https://github.com/nodesource/distributions#rpminstall

### CODE REVIEW

**Comment by jyaworski** [comment]
Would you mind fixing the few rubocop failures? It's not your fault they're there. :/

**Comment by tapsboy** [comment]
Updated .. not a ruby guy, but hopefully that was the correct resolution

**Comment by tapsboy** [comment]
Also, I see there hasn't been a new release in last 4 months. Is there any plan for that?

**Comment by bastelfreak** [comment]
There are! We're currently working on it in https://github.com/voxpupuli/puppet-nodejs/pull/224

**Pull request merged**
