### PR TITLE
Fix for NPM and Node.JS installation on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by frozenfoxx**
On Ubuntu 16.04 the system will no longer update the /etc/alternatives/node by default.  This results in applications like Yeoman not being able to execute with a `sh: 1: node: not found` error.  Setting the value to `true` solves the problem.  This is a revised pull request (in place of [https://github.com/voxpupuli/puppet-nodejs/pull/247}(https://github.com/voxpupuli/puppet-nodejs/pull/247) with new modulesync attempt, explicit definition of the legacy debian symlink and nodejs dev package variables.

This problem is also described here:  [http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu](http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu).  I cannot confirm its behavior on older Ubuntu distributions but reliably on 16.04 npm is actively removed and node's symlink not created, even when using the master from the repo.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @frozenfoxx,
thanks for the PR. Can you please rebase against our current master and drop the modulesync commit?

**Comment by bastelfreak** [comment]
Hi, we included this commit in #251

**Comment by frozenfoxx** [comment]
Thanks very much for taking care of this, I was having some real trouble figuring out how to get it to work with the modulesync.

**Comment by bastelfreak** [comment]
sure sure. When you've issues again just ping us in #voxpupuli on freenode. We normally try to take care of modulesync, so contributors don't have to deal with it.

**Pull request closed without merging**
