### PR TITLE
npmrc can take k,v

### PR DESCRIPTION
**Pull request by Poil**
Fix for #290

Add a npmrc_config hash to allow the possibility to add some configuration to /root/.npmrc

### CODE REVIEW

**Comment by ffrank** [comment]
Thanks for this patch! It looks good in general.

Weird, the failing test seems to be a linter error on some lines you didn't touch. New linter settings? Paging @juniorsysadmin and @bastelfreak.

@Poil do you think you could add some tests for your new feature, as well as some documentation?

**Comment by bastelfreak** [comment]
@ffrank yep! got introduced in the last puppet-lint update.

----

@Poil I merged https://github.com/voxpupuli/puppet-nodejs/pull/293, can you please rebase this PR?

**Comment by Poil** [comment]
Rebased

**Comment by ffrank** [comment]
Great, and thanks for the tests!

I'm merging this as is. If you could add some documentation, please feel super welcome to make another PR :)

Thank you for the contribution.

**Pull request merged**
